name: Build - Windows - CMake

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
      - "tests/**/*.cpp"
  merge_group:
  push:
    paths:
      - "src/**"
      - "tests/**/*.cpp"
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: "-j 2"

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  job:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: windows-2022-release
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Windows pre-installed MySQL
        run: Remove-Item -Recurse -Force "C:\mysql*"

      - name: Restore artifacts and get vcpkg commit
        run: |
          $json = Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $vcpkgCommitId = $json.'builtin-baseline'
          echo "VCPKG_GIT_COMMIT_ID=$vcpkgCommitId" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitURL: "https://github.com/microsoft/vcpkg.git"
          vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT_ID }}

      - name: Install latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          configurePresetAdditionalArgs: "['-DTOGGLE_BIN_FOLDER=ON']"
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: List build output (debug)
        run: Get-ChildItem -Recurse build

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: canary-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/

      - name: Run Unit Tests
        run: |
          ctest -V -R unit

      - name: Run Integration Tests
        run: |
          ctest -V -R integration
